@startuml
!include src/main/asciidoc/puml/PumlParams.puml
node "Frontend" <<Module>> {
  [/adoc] <<Route>> as route_adoc #Gold
  [AdocController] <<Controller>> as contr_adoc #orange
  [adoc.html] <<Template>> as templ_adoc #LightGreen
 
  route_adoc ..> contr_adoc : define
  route_adoc ..> templ_adoc : define
}

node "Backend" {
  [AdocEndPoint] - AdocRest
}
contr_adoc .up.> AdocRest : consume
@enduml
